
--
-- Data for Name: banks; Type: TABLE DATA; Schema: public; Owner: aman
--

COPY banks (name, id) FROM stdin;
STATE BANK OF INDIA	1
PUNJAB NATIONAL BANK	2
CANARA BANK	3
BANK OF BARODA	4
HDFC BANK	5
BANK OF INDIA	6
CENTRAL BANK OF INDIA	7
ICICI BANK LIMITED	8
UNION BANK OF INDIA	9
SYNDICATE BANK	10
ALLAHABAD BANK	11
INDIAN OVERSEAS BANK	12
AXIS BANK	13
UCO BANK	14
ANDHRA BANK	15
IDBI BANK	16
YES BANK	17
INDIAN BANK	18
ORIENTAL BANK OF COMMERCE	19
CORPORATION BANK	20
UNITED BANK OF INDIA	21
VIJAYA BANK	22
BANK OF MAHARASHTRA	23
STATE BANK OF HYDERABAD	24
DENA BANK	25
PUNJAB AND SIND BANK	26
STATE BANK OF BIKANER AND JAIPUR	27
STATE BANK OF PATIALA	28
FEDERAL BANK	29
STATE BANK OF TRAVANCORE	30
STATE BANK OF MYSORE	31
KOTAK MAHINDRA BANK LIMITED	32
INDUSIND BANK	33
JAMMU AND KASHMIR BANK LIMITED	34
SOUTH INDIAN BANK	35
KARNATAKA BANK LIMITED	36
KARUR VYSYA BANK	37
THE ANDHRA PRADESH STATE COOPERATIVE BANK LIMITED	38
PRAGATHI KRISHNA GRAMIN BANK	39
ING VYSYA BANK	40
KARNATAKA VIKAS GRAMEENA BANK	41
BANDHAN BANK LIMITED	42
KERALA GRAMIN BANK	43
CITY UNION BANK LIMITED	44
THE SHAMRAO VITHAL COOPERATIVE BANK	45
ANDHRA PRAGATHI GRAMEENA BANK	46
THE RAJASTHAN STATE COOPERATIVE BANK LIMITED	47
TAMILNAD MERCANTILE BANK LIMITED	48
LAXMI VILAS BANK	49
CATHOLIC SYRIAN BANK LIMITED	50
PRATHAMA BANK	51
SARASWAT COOPERATIVE BANK LIMITED	52
THE WEST BENGAL STATE COOPERATIVE BANK	53
DHANALAKSHMI BANK	54
THE KANGRA CENTRAL COOPERATIVE BANK LIMITED	55
RATNAKAR BANK LIMITED	56
DCB BANK LIMITED	57
THE COSMOS CO OPERATIVE BANK LIMITED	58
THE NAINITAL BANK LIMITED	59
ABHYUDAYA COOPERATIVE BANK LIMITED	60
THE AKOLA DISTRICT CENTRAL COOPERATIVE BANK	61
PUNJAB AND MAHARSHTRA COOPERATIVE BANK	62
THE THANE DISTRICT CENTRAL COOPERATIVE BANK LIMIT	63
STANDARD CHARTERED BANK	64
NKGSB COOPERATIVE BANK LIMITED	65
TJSB SAHAKARI BANK LTD	66
BHARATIYA MAHILA BANK LIMITED	67
BHARAT COOPERATIVE BANK MUMBAI LIMITED	68
THE GUJARAT STATE COOPERATIVE BANK LIMITED	69
THE MUMBAI DISTRICT CENTRAL COOPERATIVE BANK LIMI	70
THE NASIK MERCHANTS COOPERATIVE BANK LIMITED	71
MAHANAGAR COOPERATIVE BANK	72
THE SURAT DISTRICT COOPERATIVE BANK LIMITED	73
APNA SAHAKARI BANK LIMITED	74
G P PARSIK BANK	75
THE KARANATAKA STATE COOPERATIVE APEX BANK LIMITE	76
JANATA SAHAKARI BANK LIMITED	77
HSBC BANK	78
MAHARASHTRA STATE COOPERATIVE BANK	79
KALUPUR COMMERCIAL COOPERATIVE BANK	80
ALMORA URBAN COOPERATIVE BANK LIMITED	81
THE DELHI STATE COOPERATIVE BANK LIMITED	82
THE KARAD URBAN COOPERATIVE BANK LIMITED	83
BASSEIN CATHOLIC COOPERATIVE BANK LIMITED	84
DOMBIVLI NAGARI SAHAKARI BANK LIMITED	85
NAGAR URBAN CO OPERATIVE BANK	86
CITI BANK	87
NAGPUR NAGARIK SAHAKARI BANK LIMITED	88
THE MEHSANA URBAN COOPERATIVE BANK	89
KALLAPPANNA AWADE ICHALKARANJI JANATA SAHAKARI BA	90
THE KURMANCHAL NAGAR SAHAKARI BANK LIMITED	91
CAPITAL LOCAL AREA BANK LIMITED	92
CITIZEN CREDIT COOPERATIVE BANK LIMITED	93
THE A.P. MAHESH COOPERATIVE URBAN BANK LIMITED	94
SOLAPUR JANATA SAHAKARI BANK LIMITED	95
KALYAN JANATA SAHAKARI BANK	96
SHRI CHHATRAPATI RAJASHRI SHAHU URBAN COOPERATIVE	97
JALGAON JANATA SAHAKARI BANK LIMITED	98
THE JALGAON PEOPELS COOPERATIVE BANK LIMITED	99
AKOLA JANATA COMMERCIAL COOPERATIVE BANK	100
ZILA SAHAKRI BANK LIMITED GHAZIABAD	101
PRIME COOPERATIVE BANK LIMITED	102
AHMEDABAD MERCANTILE COOPERATIVE BANK	103
IDFC BANK LIMITED	104
JANASEVA SAHAKARI BANK LIMITED	105
NEW INDIA COOPERATIVE BANK LIMITED	106
THE VISHWESHWAR SAHAKARI BANK LIMITED	107
RESERVE BANK OF INDIA	108
THE TAMIL NADU STATE APEX COOPERATIVE BANK	109
THE ROYAL BANK OF SCOTLAND N V	110
JANAKALYAN SAHAKARI BANK LIMITED	111
TUMKUR GRAIN MERCHANTS COOPERATIVE BANK LIMITED	112
THE SURATH PEOPLES COOPERATIVE BANK LIMITED	113
THE THANE BHARAT SAHAKARI BANK LIMITED	114
DEUSTCHE BANK	115
THE GREATER BOMBAY COOPERATIVE BANK LIMITED	116
THE MUNICIPAL COOPERATIVE BANK LIMITED	117
NUTAN NAGARIK SAHAKARI BANK LIMITED	118
THE ZOROASTRIAN COOPERATIVE BANK LIMITED	119
TJSB SAHAKARI BANK LIMITED	120
THE VARACHHA COOPERATIVE BANK LIMITED	121
VASAI VIKAS SAHAKARI BANK LIMITED	122
SAHEBRAO DESHMUKH COOPERATIVE BANK LIMITED	123
KAPOL COOPERATIVE BANK LIMITED	124
SUTEX COOPERATIVE BANK LIMITED	125
THE HASTI COOP BANK LTD	126
JANASEVA SAHAKARI BANK BORIVLI LIMITED	127
RAJGURUNAGAR SAHAKARI BANK LIMITED	128
SURAT NATIONAL COOPERATIVE BANK LIMITED	129
DEVELOPMENT BANK OF SINGAPORE	130
THE KANGRA COOPERATIVE BANK LIMITED	131
B N P PARIBAS	132
MIZUHO CORPORATE BANK LIMITED	133
SHINHAN BANK	134
BANK OF TOKYO MITSUBISHI LIMITED	135
CREDIT AGRICOLE CORPORATE AND INVESTMENT BANK CAL	136
BANK OF AMERICA	137
BANK OF BAHARAIN AND KUWAIT BSC	138
THE BANK OF NOVA SCOTIA	139
BARCLAYS BANK	140
SOCIETE GENERALE	141
CHINATRUST COMMERCIAL BANK LIMITED	142
ABU DHABI COMMERCIAL BANK	143
SHIKSHAK SAHAKARI BANK LIMITED	144
BANK OF CEYLON	145
DOHA BANK	146
FIRSTRAND BANK LIMITED	147
DEPOSIT INSURANCE AND CREDIT GUARANTEE CORPORATIO	148
CREDIT SUISEE AG	149
INDUSTRIAL BANK OF KOREA	150
WOORI BANK	151
WESTPAC BANKING CORPORATION	152
COMMONWEALTH BANK OF AUSTRALIA	153
MASHREQBANK PSC	154
SBM BANK MAURITIUS LIMITED	155
RABOBANK INTERNATIONAL	156
EXPORT IMPORT BANK OF INDIA	157
JP MORGAN BANK	158
THE GADCHIROLI DISTRICT CENTRAL COOPERATIVE BANK 	159
AUSTRALIA AND NEW ZEALAND BANKING GROUP LIMITED	160
RAJKOT NAGRIK SAHAKARI BANK LIMITED	161
BANK INTERNASIONAL INDONESIA	162
INDUSTRIAL AND COMMERCIAL BANK OF CHINA LIMITED	163
THE SEVA VIKAS COOPERATIVE BANK LIMITED	164
UNITED OVERSEAS BANK LIMITED	165
SBER BANK	166
NATIONAL AUSTRALIA BANK LIMITED	167
DOHA BANK QSC	168
NATIONAL BANK OF ABU DHABI PJSC	169
SUMITOMO MITSUI BANKING CORPORATION	170
\.

